[project]
name = "FletAppTemplate"
version = "0.1.0"
description = "Use this template to kickstart a Flet app."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet[all]==0.28.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
